---
#
# Ansible managed
#
repository:
  description: Install and configure zabbix-proxy on your system.
  homepage: https://robertdebock.nl/
  topics: zabbix, proxy, monitoring, networking, ansible, molecule, playbook
